
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cz.abo.b2b.web.it.ui

import org.junit.jupiter.api.*

import org.openqa.selenium.By
import org.openqa.selenium.WebDriver
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions
import org.springframework.test.context.event.annotation.AfterTestClass
import kotlin.test.assertNotNull

class HomepageIT {

    companion object {
        var driver: WebDriver
        init {
            System.setProperty("webdriver.chrome.driver", this.javaClass.getResource("/chromedriver").file)
            driver = ChromeDriver(ChromeOptions())
        }


        /*@BeforeAll
        fun beforeAll() {
            System.setProperty("webdriver.chrome.driver", this.javaClass.getResource("/chromedriver").file)
            driver = ChromeDriver(ChromeOptions())
        }*/

        @AfterAll
        fun afterAll() {
            // Quit the driver to release resources
            driver.quit()
        }
    }


    @Test
    fun testHomepage() {
        driver.get("http://localhost:8080")
        assertNotNull(driver.findElement(By.xpath("//vaadin-grid-sorter[text()='Product Name']")))
    }


}